services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn Akila.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Akila.settings
      - key: PYTHON_VERSION
        value: 3.13
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString

    staticPublishPath: staticfiles
    autoDeploy: true
